services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gstcom_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - gstcom-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: gstcom_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gstcom
      MYSQL_USER: codeigniter
      MYSQL_PASSWORD: secretpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gstcom-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gstcom_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - gstcom-network
    depends_on:
      - mysql

networks:
  gstcom-network:
    driver: bridge

volumes:
  mysql_data: